include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.graphql.dart"
    - "**/*.freezed.dart"
    - "**/*.mocks.dart"
    - "**/*.gen.dart"
    - "**/*.gr.dart"
  language:
    strict-casts: true
    strict-raw-types: true
